server:
  port: 8080
  
eureka:
  client:
    service-url:
      defaultZone: http://eureka-service:8761/eureka/
    fetch-registry: true
    register-with-eureka: true

spring:
  cloud:
    gateway:
      discovery:
        locator:
          enabled: true
      routes:      
        - id: auth-service
          uri: http://auth-service:8082
          predicates:
            - Path=/auth/**
        - id: message-service
          uri: http://message-service:8083
          predicates:
            - Path=/**
          filters:
            - AuthFilter            