name: CI/CD Pipeline

on:
  push:
    branches:
      - main
      - develop
      - feature/*
  workflow_dispatch:

jobs:
  build_and_push:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        service: 
          - config-service
          - eureka-service
          - gateway-service
          - auth-service
          - message-service

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Set up JDK
        uses: actions/setup-java@v2
        with:
          java-version: '17'
          distribution: 'adopt'

      - name: Build with Maven
        run: mvn clean package -f ${{ matrix.service }}/pom.xml

      # Install doctl.
      - name: Install doctl
        uses: digitalocean/action-doctl@v2
        with:
          token: ${{ secrets.DIGITAL_OCEAN_ACCESS_TOKEN }}
      
      - name: Build container image
        run: docker build -t ${{ secrets.REGISTRY_NAME }}/${{ matrix.service }}:latest -f ${{ matrix.service }}/Dockerfile ${{ matrix.service }}
        
      - name: Log in to DigitalOcean Container Registry with short-lived credentials
        run: doctl registry login --expiry-seconds 1200
      
      - name: Push image to DigitalOcean Container Registry
        run: docker push ${{ secrets.REGISTRY_NAME }}/${{ matrix.service }}:latest      

  test:
    runs-on: ubuntu-latest
    needs: build_and_push

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Set up JDK
        uses: actions/setup-java@v2
        with:
          java-version: '17'
          distribution: 'adopt'

      - name: Run tests
        run: mvn test -f message-service/pom.xml

  deploy:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        service: 
          - config-service
          - eureka-service
          - gateway-service
          - auth-service
          - message-service
    needs: test
    steps:
      - name: List files in k8s directory
        run: ls -la $GITHUB_WORKSPACE/k8s
      
      - name: Update deployment file
        run: |
          sed -i "s|image: .*|image: ${{ secrets.REGISTRY_NAME }}/${{ matrix.service }}:latest|" $GITHUB_WORKSPACE/k8s/${{ matrix.service }}.yml
          
      - name: Save DigitalOcean kubeconfig with short-lived credentials
        run: doctl kubernetes cluster kubeconfig save --expiry-seconds 600 ${{ secrets.CLUSTER_NAME }}

      - name: Deploy to DigitalOcean Kubernetes
        run: kubectl apply -f $GITHUB_WORKSPACE/k8s/${{ matrix.service }}.yml

      - name: Verify deployment
        run: kubectl rollout status deployment/${{ matrix.service }}
